[package]
name = "rocket_prometheus"
version = "0.1.0"
authors = ["Ben Sully <ben.sully@yougov.com>"]
edition = "2018"

[dependencies]
prometheus = "0.5"
rocket = "0.4.0"

[dev-dependencies]
lazy_static = "1.3.0"
rocket_contrib = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
