[package]
name = "rocket_prometheus"
description = """
Prometheus instrumentation for Rocket applications.
"""
version = "0.4.0"
authors = ["Ben Sully <ben@bsull.io>"]
repository = "https://github.com/sd2k/rocket_prometheus"
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["rocket", "prometheus", "instrumentation", "monitoring"]
readme = "README.md"

[dependencies]
prometheus = "0.8"
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "async" }

[dev-dependencies]
once_cell = "1.2.0"
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", branch = "async" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[badges]
maintenance = { status = "passively-maintained" }
